# Generated by Django 5.1.6 on 2025-02-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='preview',
            field=models.ImageField(default=1, upload_to='images/%Y/%n/m'),
            preserve_default=False,
        ),
    ]
