# Generated by Django 5.1.6 on 2025-02-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.ImageField(upload_to=''),
        ),
    ]
