# Generated by Django 5.1.6 on 2025-02-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_remove_film_country_alter_actor_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='post',
        ),
        migrations.AlterField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(related_name='actor', to='films.actor'),
        ),
    ]
