# Generated by Django 5.1.6 on 2025-02-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_remove_film_post_alter_film_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%n/%t'),
        ),
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.ImageField(upload_to='preview/%Y/%n/%t'),
        ),
    ]
