# Generated by Django 5.1.6 on 2025-02-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_actor_photo_alter_film_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.ImageField(upload_to='photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.ImageField(upload_to='preview/%Y/%m/%d'),
        ),
    ]
