# Generated by Django 5.1.6 on 2025-02-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_alter_actor_photo_alter_film_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
    ]
