# Generated by Django 5.1.6 on 2025-02-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_remove_film_actor_remove_category_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='genres',
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.SmallIntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
