# Generated by Django 5.1.6 on 2025-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_remove_film_genres_film_rating_delete_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
