# Generated by Django 5.1.6 on 2025-02-09 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_alter_film_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.CharField(choices=[(1, 'Мультфильм'), (2, 'Фильм'), (3, 'Сериал'), (4, 'Мультсериал'), (5, 'Аниме')], default=1, max_length=128, verbose_name='Жанр'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.AlterField(
            model_name='film',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.ImageField(upload_to='preview/%Y/%m/%d', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='films.category', verbose_name='Категория'),
        ),
    ]
