# Generated by Django 5.1.6 on 2025-02-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0013_alter_film_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
