# Generated by Django 5.1.6 on 2025-02-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0015_actor_film_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='preview/%Y/%m/%d', verbose_name='Превью'),
        ),
    ]
