# Generated by Django 5.1.6 on 2025-02-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0016_alter_film_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='actors', to='films.actor', verbose_name='Актеры'),
        ),
    ]
