# Generated by Django 5.1.6 on 2025-02-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0017_alter_film_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='films.actor', verbose_name='Актеры'),
        ),
    ]
