# Generated by Django 5.1.6 on 2025-02-23 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0018_alter_film_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='rating',
        ),
        migrations.AddField(
            model_name='film',
            name='average_rating',
            field=models.FloatField(default=1, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.IntegerField(choices=[(1, 'Мультфильм'), (2, 'Фильм'), (3, 'Сериал'), (4, 'Мультсериал'), (5, 'Аниме')], verbose_name='Жанр'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Рейтинг')),
                ('film', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.film', verbose_name='Фильм')),
            ],
        ),
    ]
