# Generated by Django 5.1.6 on 2025-02-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0019_remove_film_rating_film_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='average_rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
    ]
