# Generated by Django 5.1.6 on 2025-02-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0020_alter_film_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='genres',
            new_name='genre',
        ),
    ]
