# Generated by Django 5.1.6 on 2025-02-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_status',
            field=models.PositiveSmallIntegerField(choices=[('Пользователь', 'Пользователь'), ('Администратор', 'Администратор')], default=0),
        ),
    ]
