# Generated by Django 5.1.6 on 2025-02-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('users', '0006_customtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomToken',
            new_name='Bearer',
        ),
    ]
